[build]
  publish = "dist"           # El directorio donde se guardan los archivos generados
  command = "npm run build"  # Comando para construir tu aplicación

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
