import '../pages/Contacto.scss'
import { useState } from 'react';

export const useContactoFormulario = () => {
    const [formData, setFormData] = useState({
        primerNombre: '',
        segundoNombre: '',
        primerApellido: '',
        segundoApellido: '',
        edad: '',
        email: '',
        sexo: ''
    });

    const [nacionalidad, setNacionalidad] = useState('');
    const [prefijo, setPrefijo] = useState('');
    const [telefono, setTelefono] = useState('');

    const nacionalidadesYPrefijos = [
        { nombre: "Selecciona tu país", codigo: "", prefijo: "" },
        { nombre: "Afganistán", codigo: "AF", prefijo: "+93" },
        { nombre: "Albania", codigo: "AL", prefijo: "+355" },
        { nombre: "Alemania", codigo: "DE", prefijo: "+49" },
        { nombre: "Andorra", codigo: "AD", prefijo: "+376" },
        { nombre: "Angola", codigo: "AO", prefijo: "+244" },
        { nombre: "Antigua y Barbuda", codigo: "AG", prefijo: "+1-268" },
        { nombre: "Arabia Saudita", codigo: "SA", prefijo: "+966" },
        { nombre: "Argelia", codigo: "DZ", prefijo: "+213" },
        { nombre: "Argentina", codigo: "AR", prefijo: "+54" },
        { nombre: "Armenia", codigo: "AM", prefijo: "+374" },
        { nombre: "Australia", codigo: "AU", prefijo: "+61" },
        { nombre: "Austria", codigo: "AT", prefijo: "+43" },
        { nombre: "Azerbaiyán", codigo: "AZ", prefijo: "+994" },
        { nombre: "Bahamas", codigo: "BS", prefijo: "+1-242" },
        { nombre: "Baréin", codigo: "BH", prefijo: "+973" },
        { nombre: "Bangladés", codigo: "BD", prefijo: "+880" },
        { nombre: "Barbados", codigo: "BB", prefijo: "+1-246" },
        { nombre: "Bélgica", codigo: "BE", prefijo: "+32" },
        { nombre: "Belice", codigo: "BZ", prefijo: "+501" },
        { nombre: "Benín", codigo: "BJ", prefijo: "+229" },
        { nombre: "Bielorrusia", codigo: "BY", prefijo: "+375" },
        { nombre: "Birmania", codigo: "MM", prefijo: "+95" },
        { nombre: "Bolivia", codigo: "BO", prefijo: "+591" },
        { nombre: "Bosnia y Herzegovina", codigo: "BA", prefijo: "+387" },
        { nombre: "Botsuana", codigo: "BW", prefijo: "+267" },
        { nombre: "Brasil", codigo: "BR", prefijo: "+55" },
        { nombre: "Brunéi", codigo: "BN", prefijo: "+673" },
        { nombre: "Bulgaria", codigo: "BG", prefijo: "+359" },
        { nombre: "Burkina Faso", codigo: "BF", prefijo: "+226" },
        { nombre: "Burundi", codigo: "BI", prefijo: "+257" },
        { nombre: "Bután", codigo: "BT", prefijo: "+975" },
        { nombre: "Cabo Verde", codigo: "CV", prefijo: "+238" },
        { nombre: "Camboya", codigo: "KH", prefijo: "+855" },
        { nombre: "Camerún", codigo: "CM", prefijo: "+237" },
        { nombre: "Canadá", codigo: "CA", prefijo: "+1" },
        { nombre: "Catar", codigo: "QA", prefijo: "+974" },
        { nombre: "Chad", codigo: "TD", prefijo: "+235" },
        { nombre: "Chile", codigo: "CL", prefijo: "+56" },
        { nombre: "China", codigo: "CN", prefijo: "+86" },
        { nombre: "Chipre", codigo: "CY", prefijo: "+357" },
        { nombre: "Colombia", codigo: "CO", prefijo: "+57" },
        { nombre: "Comoras", codigo: "KM", prefijo: "+269" },
        { nombre: "Corea del Norte", codigo: "KP", prefijo: "+850" },
        { nombre: "Corea del Sur", codigo: "KR", prefijo: "+82" },
        { nombre: "Costa de Marfil", codigo: "CI", prefijo: "+225" },
        { nombre: "Costa Rica", codigo: "CR", prefijo: "+506" },
        { nombre: "Croacia", codigo: "HR", prefijo: "+385" },
        { nombre: "Cuba", codigo: "CU", prefijo: "+53" },
        { nombre: "Dinamarca", codigo: "DK", prefijo: "+45" },
        { nombre: "Dominica", codigo: "DM", prefijo: "+1-767" },
        { nombre: "Ecuador", codigo: "EC", prefijo: "+593" },
        { nombre: "Egipto", codigo: "EG", prefijo: "+20" },
        { nombre: "El Salvador", codigo: "SV", prefijo: "+503" },
        { nombre: "Emiratos Árabes Unidos", codigo: "AE", prefijo: "+971" },
        { nombre: "Eritrea", codigo: "ER", prefijo: "+291" },
        { nombre: "Eslovaquia", codigo: "SK", prefijo: "+421" },
        { nombre: "Eslovenia", codigo: "SI", prefijo: "+386" },
        { nombre: "España", codigo: "ES", prefijo: "+34" },
        { nombre: "Estados Unidos", codigo: "US", prefijo: "+1" },
        { nombre: "Estonia", codigo: "EE", prefijo: "+372" },
        { nombre: "Esuatini", codigo: "SZ", prefijo: "+268" },
        { nombre: "Etiopía", codigo: "ET", prefijo: "+251" },
        { nombre: "Filipinas", codigo: "PH", prefijo: "+63" },
        { nombre: "Finlandia", codigo: "FI", prefijo: "+358" },
        { nombre: "Fiyi", codigo: "FJ", prefijo: "+679" },
        { nombre: "Francia", codigo: "FR", prefijo: "+33" },
        { nombre: "Gabón", codigo: "GA", prefijo: "+241" },
        { nombre: "Gambia", codigo: "GM", prefijo: "+220" },
        { nombre: "Georgia", codigo: "GE", prefijo: "+995" },
        { nombre: "Ghana", codigo: "GH", prefijo: "+233" },
        { nombre: "Granada", codigo: "GD", prefijo: "+1-473" },
        { nombre: "Grecia", codigo: "GR", prefijo: "+30" },
        { nombre: "Guatemala", codigo: "GT", prefijo: "+502" },
        { nombre: "Guinea", codigo: "GN", prefijo: "+224" },
        { nombre: "Guinea-Bisáu", codigo: "GW", prefijo: "+245" },
        { nombre: "Guinea Ecuatorial", codigo: "GQ", prefijo: "+240" },
        { nombre: "Guyana", codigo: "GY", prefijo: "+592" },
        { nombre: "Haití", codigo: "HT", prefijo: "+509" },
        { nombre: "Honduras", codigo: "HN", prefijo: "+504" },
        { nombre: "Hungría", codigo: "HU", prefijo: "+36" },
        { nombre: "India", codigo: "IN", prefijo: "+91" },
        { nombre: "Indonesia", codigo: "ID", prefijo: "+62" },
        { nombre: "Irak", codigo: "IQ", prefijo: "+964" },
        { nombre: "Irán", codigo: "IR", prefijo: "+98" },
        { nombre: "Irlanda", codigo: "IE", prefijo: "+353" },
        { nombre: "Islandia", codigo: "IS", prefijo: "+354" },
        { nombre: "Israel", codigo: "IL", prefijo: "+972" },
        { nombre: "Italia", codigo: "IT", prefijo: "+39" },
        { nombre: "Jamaica", codigo: "JM", prefijo: "+1-876" },
        { nombre: "Japón", codigo: "JP", prefijo: "+81" },
        { nombre: "Jordania", codigo: "JO", prefijo: "+962" },
        { nombre: "Kazajistán", codigo: "KZ", prefijo: "+7" },
        { nombre: "Kenia", codigo: "KE", prefijo: "+254" },
        { nombre: "Kirguistán", codigo: "KG", prefijo: "+996" },
        { nombre: "Kiribati", codigo: "KI", prefijo: "+686" },
        { nombre: "Kosovo", codigo: "XK", prefijo: "+383" },
        { nombre: "Kuwait", codigo: "KW", prefijo: "+965" },
        { nombre: "Laos", codigo: "LA", prefijo: "+856" },
        { nombre: "Lesoto", codigo: "LS", prefijo: "+266" },
        { nombre: "Letonia", codigo: "LV", prefijo: "+371" },
        { nombre: "Líbano", codigo: "LB", prefijo: "+961" },
        { nombre: "Liberia", codigo: "LR", prefijo: "+231" },
        { nombre: "Libia", codigo: "LY", prefijo: "+218" },
        { nombre: "Liechtenstein", codigo: "LI", prefijo: "+423" },
        { nombre: "Lituania", codigo: "LT", prefijo: "+370" },
        { nombre: "Luxemburgo", codigo: "LU", prefijo: "+352" },
        { nombre: "Madagascar", codigo: "MG", prefijo: "+261" },
        { nombre: "Malasia", codigo: "MY", prefijo: "+60" },
        { nombre: "Malaui", codigo: "MW", prefijo: "+265" },
        { nombre: "Maldivas", codigo: "MV", prefijo: "+960" },
        { nombre: "Malí", codigo: "ML", prefijo: "+223" },
        { nombre: "Malta", codigo: "MT", prefijo: "+356" },
        { nombre: "Marruecos", codigo: "MA", prefijo: "+212" },
        { nombre: "Islas Marshall", codigo: "MH", prefijo: "+692" },
        { nombre: "Mauricio", codigo: "MU", prefijo: "+230" },
        { nombre: "Mauritania", codigo: "MR", prefijo: "+222" },
        { nombre: "México", codigo: "MX", prefijo: "+52" },
        { nombre: "Micronesia", codigo: "FM", prefijo: "+691" },
        { nombre: "Moldavia", codigo: "MD", prefijo: "+373" },
        { nombre: "Mónaco", codigo: "MC", prefijo: "+377" },
        { nombre: "Mongolia", codigo: "MN", prefijo: "+976" },
        { nombre: "Montenegro", codigo: "ME", prefijo: "+382" },
        { nombre: "Mozambique", codigo: "MZ", prefijo: "+258" },
        { nombre: "Namibia", codigo: "NA", prefijo: "+264" },
        { nombre: "Nauru", codigo: "NR", prefijo: "+674" },
        { nombre: "Nepal", codigo: "NP", prefijo: "+977" },
        { nombre: "Nicaragua", codigo: "NI", prefijo: "+505" },
        { nombre: "Níger", codigo: "NE", prefijo: "+227" },
        { nombre: "Nigeria", codigo: "NG", prefijo: "+234" },
        { nombre: "Noruega", codigo: "NO", prefijo: "+47" },
        { nombre: "Nueva Zelanda", codigo: "NZ", prefijo: "+64" },
        { nombre: "Omán", codigo: "OM", prefijo: "+968" },
        { nombre: "Países Bajos", codigo: "NL", prefijo: "+31" },
        { nombre: "Pakistán", codigo: "PK", prefijo: "+92" },
        { nombre: "Palaos", codigo: "PW", prefijo: "+680" },
        { nombre: "Panamá", codigo: "PA", prefijo: "+507" },
        { nombre: "Papúa Nueva Guinea", codigo: "PG", prefijo: "+675" },
        { nombre: "Paraguay", codigo: "PY", prefijo: "+595" },
        { nombre: "Perú", codigo: "PE", prefijo: "+51" },
        { nombre: "Polonia", codigo: "PL", prefijo: "+48" },
        { nombre: "Portugal", codigo: "PT", prefijo: "+351" },
        { nombre: "Reino Unido", codigo: "GB", prefijo: "+44" },
        { nombre: "República Centroafricana", codigo: "CF", prefijo: "+236" },
        { nombre: "República Checa", codigo: "CZ", prefijo: "+420" },
        { nombre: "República del Congo", codigo: "CG", prefijo: "+242" },
        { nombre: "República Democrática del Congo", codigo: "CD", prefijo: "+243" },
        { nombre: "República Dominicana", codigo: "DO", prefijo: "+1-809, +1-829, +1-849" },
        { nombre: "Ruanda", codigo: "RW", prefijo: "+250" },
        { nombre: "Rumania", codigo: "RO", prefijo: "+40" },
        { nombre: "Rusia", codigo: "RU", prefijo: "+7" },
        { nombre: "Samoa", codigo: "WS", prefijo: "+685" },
        { nombre: "San Cristóbal y Nieves", codigo: "KN", prefijo: "+1-869" },
        { nombre: "San Marino", codigo: "SM", prefijo: "+378" },
        { nombre: "San Vicente y las Granadinas", codigo: "VC", prefijo: "+1-784" },
        { nombre: "Santa Lucía", codigo: "LC", prefijo: "+1-758" },
        { nombre: "Santo Tomé y Príncipe", codigo: "ST", prefijo: "+239" },
        { nombre: "Senegal", codigo: "SN", prefijo: "+221" },
        { nombre: "Serbia", codigo: "RS", prefijo: "+381" },
        { nombre: "Seychelles", codigo: "SC", prefijo: "+248" },
        { nombre: "Sierra Leona", codigo: "SL", prefijo: "+232" },
        { nombre: "Singapur", codigo: "SG", prefijo: "+65" },
        { nombre: "Siria", codigo: "SY", prefijo: "+963" },
        { nombre: "Somalia", codigo: "SO", prefijo: "+252" },
        { nombre: "Sri Lanka", codigo: "LK", prefijo: "+94" },
        { nombre: "Sudáfrica", codigo: "ZA", prefijo: "+27" },
        { nombre: "Sudán", codigo: "SD", prefijo: "+249" },
        { nombre: "Sudán del Sur", codigo: "SS", prefijo: "+211" },
        { nombre: "Suecia", codigo: "SE", prefijo: "+46" },
        { nombre: "Suiza", codigo: "CH", prefijo: "+41" },
        { nombre: "Surinam", codigo: "SR", prefijo: "+597" },
        { nombre: "Tailandia", codigo: "TH", prefijo: "+66" },
        { nombre: "Tanzania", codigo: "TZ", prefijo: "+255" },
        { nombre: "Tayikistán", codigo: "TJ", prefijo: "+992" },
        { nombre: "Timor Oriental", codigo: "TL", prefijo: "+670" },
        { nombre: "Togo", codigo: "TG", prefijo: "+228" },
        { nombre: "Tonga", codigo: "TO", prefijo: "+676" },
        { nombre: "Trinidad y Tobago", codigo: "TT", prefijo: "+1-868" },
        { nombre: "Túnez", codigo: "TN", prefijo: "+216" },
        { nombre: "Turkmenistán", codigo: "TM", prefijo: "+993" },
        { nombre: "Turquía", codigo: "TR", prefijo: "+90" },
        { nombre: "Tuvalu", codigo: "TV", prefijo: "+688" },
        { nombre: "Ucrania", codigo: "UA", prefijo: "+380" },
        { nombre: "Uganda", codigo: "UG", prefijo: "+256" },
        { nombre: "Uruguay", codigo: "UY", prefijo: "+598" },
        { nombre: "Uzbekistán", codigo: "UZ", prefijo: "+998" },
        { nombre: "Vanuatu", codigo: "VU", prefijo: "+678" },
        { nombre: "Vaticano", codigo: "VA", prefijo: "+379" },
        { nombre: "Venezuela", codigo: "VE", prefijo: "+58" },
        { nombre: "Vietnam", codigo: "VN", prefijo: "+84" },
        { nombre: "Yemen", codigo: "YE", prefijo: "+967" },
        { nombre: "Yibuti", codigo: "DJ", prefijo: "+253" },
        { nombre: "Zambia", codigo: "ZM", prefijo: "+260" },
        { nombre: "Zimbabue", codigo: "ZW", prefijo: "+263" }
        
    ];

    const handleInputChange = (e) => {
        const { name, value } = e.target;
        setFormData({
            ...formData,
            [name]: value
        });
    };

    const handleNacionalidadChange = (e) => {
        const selectedCountry = nacionalidadesYPrefijos.find(country => country.codigo === e.target.value);
        setNacionalidad(selectedCountry.nombre);
        setPrefijo(selectedCountry.prefijo);
    };

    const handleSubmit = (e) => {
        e.preventDefault();
        const datosCompletos = { ...formData, nacionalidad, telefono };
        console.log(datosCompletos);
        
    };

    return {
        formData,
        nacionalidadesYPrefijos,
        nacionalidad,
        prefijo,
        telefono,
        setTelefono,
        handleSubmit,
        handleInputChange,
        handleNacionalidadChange
    };
};